name: 🐛 Bug Report
description: Report a bug in the project
title: "bug: [Short Description of the Bug]"
labels: ["bug", "triage"]
projects: ["LULA-LOOP/12"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        

  - type: textarea
    id: description
    attributes:
      label: Describe the Feature Request
      description: A clear and concise description of what the feature does.
    validations:
      required: true

  - type: textarea
    id: current_behavior
    attributes:
      label: Current Behavior
      description: Describe the current behavior of the application when the bug occurs. Be as detailed as possible.
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen instead.
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide a step-by-step list of actions that are required to reproduce the bug. This should be detailed enough that someone else can follow it to encounter the same issue.
      placeholder: |
        1. Go to "..."
        2. Click on "..."
        3. Scroll down to "..."
        4. See error
    validations:
      required: true

  - type: input
    id: reproduction_link
    attributes:
      label: Reproduction Link
      description: Provide the URL where the bug occurred.
    validations:
      required: true

  - type: dropdown
    id: Environment
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - iOS
        - Android
        - Huawei

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshot (Optional)
      description: Attach a screenshot if it helps to illustrate the bug.

  - type: textarea
    id: additional_information
    attributes:
      label: Additional Information
      description: Provide any additional information that might help in diagnosing and fixing the bug. This could include screenshots, logs, or any other relevant data.
